#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bootstraps the Pull.fm staging application node.
#
# Idempotent: safe to re-run. Run as root ON THE NODE, from a directory holding
# this repository's infra/staging/app contents, with these already placed:
#
#   /etc/pullfm/bff.env              application configuration and secrets
#   /etc/ssl/pullfm/origin.pem       Cloudflare Origin CA certificate
#   /etc/ssl/pullfm/origin.key       its private key
#   /etc/ssl/pullfm/origin-pull-ca.pem   Cloudflare's origin-pull CA
#
# None of those four are in git and none ever will be.
# ---------------------------------------------------------------------------
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root" >&2
  exit 1
fi

for f in /etc/pullfm/bff.env /etc/ssl/pullfm/origin.pem /etc/ssl/pullfm/origin.key /etc/ssl/pullfm/origin-pull-ca.pem; do
  [ -f "$f" ] || {
    echo "missing $f" >&2
    exit 1
  }
done

# /etc/pullfm/alert.env is NOT in that list, and the asymmetry is deliberate.
# The four files above are ones the node cannot serve traffic without, so a
# missing one must stop the bootstrap. The alert channel is one the node can
# serve traffic without, so refusing to bootstrap over it would trade a working
# origin for a notification channel. It is still a real gap, so it is loud
# rather than fatal: an unarmed node runs its timers and tells nobody when they
# fail, which is the exact defect this environment exists to stop shipping.
if [ ! -f /etc/pullfm/alert.env ]; then
  echo "WARNING: /etc/pullfm/alert.env is missing. The watchdog and the four" >&2
  echo "job timers will run and will NOT be able to notify anyone." >&2
  echo "Arm it with: infra/observability/install-alert-env.sh --stdout | ssh ..." >&2
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-v2 nginx
systemctl enable --now docker

# --- the Postgres client, needed by TWO host jobs --------------------------
#
# A function rather than a block inside `if [ -d backup ]`, because the
# MusicBrainz loader needs `psql` for the same reason the dump needs `pg_dump`
# and the two are shipped independently. It was inline in the backup section
# until 2026-07-29; a node converged with mb-loader but without backup would
# then have installed a canonical-refresh unit onto a node with no psql at all,
# which fails in the loader's own precondition check - loudly, but for a reason
# that has nothing to do with the loader.
#
# PGMAJOR IS A FACT ABOUT THE SERVER, NOT A PREFERENCE. Neon runs Postgres 18
# (infra/neon/variables.tf pg_version, ForceNew; `select version()` on the
# staging branch answers 18.4). noble ships postgresql-client-16 at the newest,
# and pg_dump REFUSES OUTRIGHT to dump a server newer than itself, so the
# distribution package would have produced a unit that runs nightly, fails
# nightly, and alerts nightly. psql is more forgiving - a client 16 `\copy` of
# all 31,554,198 canonical rows into the 18 branch was measured working - so the
# wrong client degrades the loader and stops the backup. Both get the right one.
#
# THE TEST IS THE MAJOR VERSION AND NOT `command -v pg_dump`, and that is a
# correction rather than a preference. It was a presence check for one hour on
# 2026-07-29, during which something else on this node installed
# `postgresql-client` - the unversioned metapackage, which on noble pulls client
# 16. The presence check then passed, the install skipped, and the node ended up
# with a backup unit and a pg_dump that cannot dump the server it points at. A
# dependency check that a WRONG version satisfies is not a check.
PGDG_KEY_FPR=B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
PGMAJOR=18

ensure_pg_client() {
  [ -x "/usr/lib/postgresql/${PGMAJOR}/bin/pg_dump" ] && return 0

  echo "installing postgresql-client-${PGMAJOR} from PGDG (Neon runs Postgres ${PGMAJOR})"
  apt-get install -y -qq curl ca-certificates gnupg
  curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc |
    gpg --dearmor -o /tmp/pgdg.gpg
  # Verify the key BEFORE it is trusted to sign packages. A keyring fetched over
  # TLS and installed unread trusts whoever answered the request.
  if ! gpg --show-keys --with-colons /tmp/pgdg.gpg | grep -q "^fpr:::::::::${PGDG_KEY_FPR}:"; then
    echo "PGDG signing key does not have the expected fingerprint" >&2
    rm -f /tmp/pgdg.gpg
    exit 1
  fi
  install -m 0644 /tmp/pgdg.gpg /usr/share/keyrings/pgdg.gpg
  rm -f /tmp/pgdg.gpg
  . /etc/os-release
  cat >/etc/apt/sources.list.d/pgdg.list <<PGDG
# Generated by bootstrap.sh. Postgres CLIENT tools only; no server is installed.
deb [signed-by=/usr/share/keyrings/pgdg.gpg] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main
PGDG
  chmod 0644 /etc/apt/sources.list.d/pgdg.list
  apt-get update -qq
  apt-get install -y -qq "postgresql-client-${PGMAJOR}"
}

# A drop-in rather than an edit to the unit, for the same reason the watchdog
# gets one: the unit describes what the job does and belongs to infra/backup/ or
# infra/mb-loader/, while WHICH pg_dump and WHICH psql answer on this node is a
# fact about this node's shape. /usr/bin/pg_dump and /usr/bin/psql are
# `pg_wrapper`, which dispatches to whichever major version it decides is
# current, and that decision is made by whatever else happens to be installed.
# Prepending the versioned bindir makes these jobs use Postgres ${PGMAJOR}'s
# binaries no matter what else lands here, and leaves /usr/bin alone for
# everything else on the node.
#
# NOT hard-coded into the committed unit files, deliberately: ${PGMAJOR} lives
# here, and duplicating the literal into two unit files would mean three places
# to change and two of them silently stale.
install_pg_path_dropin() {
  local d="/etc/systemd/system/${1:?usage: install_pg_path_dropin <unit>}.d"
  install -d -m 0755 "${d}"
  cat >"${d}/10-pg-path.conf" <<PGPATH
# Generated by bootstrap.sh. Do not edit.
[Service]
Environment=PATH=/usr/lib/postgresql/${PGMAJOR}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGPATH
  chmod 0644 "${d}/10-pg-path.conf"
}

# --- permissions on material that must not be world readable ---------------
chmod 0750 /etc/pullfm
chmod 0600 /etc/pullfm/bff.env
chmod 0750 /etc/ssl/pullfm
chmod 0640 /etc/ssl/pullfm/origin.key
chown -R root:www-data /etc/ssl/pullfm

# --- nginx -----------------------------------------------------------------
# Ubuntu's stock default site is a catch-all on port 80 without proxy_protocol,
# which would answer the load balancer's health check before our own server
# block ever sees it, and answer it with a 400.
rm -f /etc/nginx/sites-enabled/default

# --- ingress mode ----------------------------------------------------------
# Two supported paths, and the listener must match the one Terraform actually
# provisioned. Getting this wrong is not subtle in its effect and is very subtle
# in its appearance: a listener that does not expect a PROXY header reads it as
# the first line of an HTTP request and answers 400 to EVERY connection, which
# looks exactly like an application bug.
#
#   direct  (default)  Cloudflare talks straight to this node. Matches
#                      enable_load_balancer = false, which is the pre-launch
#                      shape: one application node, no EUR 8.49/mo load balancer
#                      round-robining across a single target.
#   lb                 A Hetzner load balancer fronts the node with TCP
#                      passthrough and proxyprotocol = true. Matches
#                      enable_load_balancer = true, which is required for more
#                      than one application node.
#
# Client IP is unaffected by the choice. The PROXY header carries the CLOUDFLARE
# EDGE address, never the client's; the client address comes from
# CF-Connecting-IP and is forwarded to the BFF either way. Per-IP rate limiting
# and audit_log.ip see the same values on both paths.
PULLFM_INGRESS=${PULLFM_INGRESS:-direct}

case "${PULLFM_INGRESS}" in
  direct) PROXY_TOKEN="" ;;
  lb) PROXY_TOKEN="proxy_protocol" ;;
  *)
    echo "PULLFM_INGRESS must be 'direct' or 'lb', got '${PULLFM_INGRESS}'" >&2
    exit 1
    ;;
esac

# Substitution is restricted to `listen` lines so the placeholder survives in
# the template's own documentation. The count assertions are the point of doing
# it this way: a future edit that adds a listener and forgets the placeholder,
# or renames it, fails the bootstrap instead of producing a config that starts
# and rejects every request.
EXPECTED_LISTENERS=4
found=$(grep -cE '^[[:space:]]*listen .*@PROXY@' nginx-pullfm.conf.in || true)
if [ "${found}" -ne "${EXPECTED_LISTENERS}" ]; then
  echo "expected ${EXPECTED_LISTENERS} templated listen directives, found ${found}" >&2
  exit 1
fi

sed -E "/^[[:space:]]*listen /s/@PROXY@/${PROXY_TOKEN}/" \
  nginx-pullfm.conf.in >/tmp/pullfm-nginx.rendered

if grep -qE '^[[:space:]]*listen .*@PROXY@' /tmp/pullfm-nginx.rendered; then
  echo "a listen directive still carries the placeholder after rendering" >&2
  exit 1
fi

install -m 0644 /tmp/pullfm-nginx.rendered /etc/nginx/sites-available/pullfm
rm -f /tmp/pullfm-nginx.rendered
ln -sf /etc/nginx/sites-available/pullfm /etc/nginx/sites-enabled/pullfm

# The other half of the same decision, written in the same step so the two
# cannot be edited apart. On the load-balancer path realip rewrites $remote_addr
# from the PROXY header to the Cloudflare edge address; on the direct path
# $remote_addr is already that address and any realip rule here would be wrong.
# Either way the allowlist reads $remote_addr, which is what lets one template
# serve both paths.
if [ "${PULLFM_INGRESS}" = "lb" ]; then
  cat >/etc/nginx/conf.d/00-pullfm-ingress.conf <<'INGRESS'
# Generated by bootstrap.sh for PULLFM_INGRESS=lb. Do not edit.
set_real_ip_from 10.20.1.0/24;
real_ip_header proxy_protocol;
INGRESS
else
  cat >/etc/nginx/conf.d/00-pullfm-ingress.conf <<'INGRESS'
# Generated by bootstrap.sh for PULLFM_INGRESS=direct. Do not edit.
# No realip rule: Cloudflare is the L3 peer, so $remote_addr is already the
# edge address the allowlist checks. Adding a CF-Connecting-IP realip rule here
# would rewrite $remote_addr to the CLIENT address and the allowlist would then
# 403 every real user.
INGRESS
fi
chmod 0644 /etc/nginx/conf.d/00-pullfm-ingress.conf

install -m 0755 pullfm-cf-ranges /usr/local/bin/pullfm-cf-ranges
# Must run before the first `nginx -t`: the allowlist file defines the
# $cloudflare_edge variable the site config references, and nginx refuses to
# start with an undefined variable.
/usr/local/bin/pullfm-cf-ranges || {
  echo "could not build the Cloudflare allowlist" >&2
  exit 1
}

nginx -t
systemctl enable --now nginx
systemctl reload nginx

# --- application -----------------------------------------------------------
# The maintenance flag directory. 0755 and empty: the only thing that ever lives
# here is a zero-byte marker, and it is bind-mounted read-only into the BFF so
# `touch` on the node is a lever the container can see. It is separate from
# /etc/pullfm precisely so that mount does not carry the secrets.
install -d -m 0755 /etc/pullfm/flags

install -d -m 0755 /opt/pullfm
install -m 0644 docker-compose.yml /opt/pullfm/docker-compose.yml
install -m 0755 pullfm-deploy /usr/local/bin/pullfm-deploy

install -m 0644 systemd/pullfm-deploy.service /etc/systemd/system/
install -m 0644 systemd/pullfm-deploy.timer /etc/systemd/system/
install -m 0644 systemd/pullfm-cf-ranges.service /etc/systemd/system/
install -m 0644 systemd/pullfm-cf-ranges.timer /etc/systemd/system/

# --- scheduled background jobs ---------------------------------------------
# Four jobs that bound something: two retention windows the privacy policy
# states, one unconsented-record window with no lawful basis to exceed, and the
# cache warm that keeps the request path from spending a global 1 req/s provider
# budget on a page render. Each is a COMMAND, run in a one-shot container built
# from the digest that is currently serving, never an in-process timer. The
# reasoning, the cadences and the exit-code contract are in docs/RUNBOOK-JOBS.md
# and in the header of each entrypoint under apps/bff/src/scripts/.
#
# The timers are installed on every application node rather than pinned to one.
# That is safe because each job takes a Postgres advisory lock on a pinned
# connection and a second invocation DECLINES rather than racing, and it is the
# only arrangement that survives a node being replaced. Pre-launch there is one
# application node, so the lock is a belt on a second node that does not exist
# yet; see infra/terraform/envs/*/main.tf for the guard that keeps it that way.
install -m 0755 pullfm-job /usr/local/bin/pullfm-job
install -m 0755 pullfm-job-alert /usr/local/bin/pullfm-job-alert

install -m 0644 systemd/pullfm-job-alert@.service /etc/systemd/system/
for job in warm-cache sweep-expired purge-audit reap-unverified; do
  install -m 0644 "systemd/pullfm-${job}.service" /etc/systemd/system/
  install -m 0644 "systemd/pullfm-${job}.timer" /etc/systemd/system/
done

# --- the scheduled database backup -----------------------------------------
#
# WHAT WAS WRONG. `docs/api/deletion-and-backups.md` states a three-layer backup
# position and gives the object-storage layer a retention of "35 days
# scheduled". There was no scheduler. Enumerated on this node on 2026-07-29:
# seven pullfm timers (deploy, cf-ranges, watchdog and the four application
# jobs) and not one of them a backup; nothing in /etc/systemd/system matching
# backup, ledger or erasure; /etc/cron.d holding only distribution defaults; and
# `infra/backup/pullfm-backup.sh` not present on the node at all. Every dump in
# the backups bucket had been taken by hand from a workstation. That is
# PULLFM-RISK-012: the documented control existed in git, which is why reading
# the repository would have concluded it was present.
#
# WHY THIS SHAPE. The units were already written, and correctly - `OnFailure=`
# in [Unit], `TimeoutStartSec=` rather than the `RuntimeMaxSec=` systemd
# discards on a oneshot, `ConditionPathExists=` so an unconfigured node skips
# rather than alerts. They were simply never installed, because
# `infra/backup/README.md` recorded the install as belonging to `infra/staging/`
# and nothing here had claimed it. This section claims it, and follows the
# application-job loop above exactly: install the pair, then `enable --now` the
# TIMER and never the service.
#
# WHY ONLY ONE OF THE FOUR. `infra/backup/systemd/` holds four units and the
# other three are deliberately left out rather than forgotten. A unit installed
# on a node that cannot run it correctly is worse than no unit: it fails on a
# schedule, and an operator paged weekly by a job that was never going to work
# stops reading the pages that matter.
#
#   pullfm-backup-retention  CANNOT WORK WITH THIS NODE'S CREDENTIAL, measured
#                            rather than assumed. Run here on 2026-07-29 it
#                            reported four MISSING lifecycle rules; the real
#                            answer was AccessDenied on
#                            GetBucketLifecycleConfiguration. Lifecycle is a
#                            bucket-ADMIN operation in R2 and the node holds a
#                            bucket-scoped OBJECT token, which is the whole point
#                            of PULLFM-RISK-013. Widening the token to satisfy a
#                            weekly check would undo the fix that risk records.
#                            The check belongs on an operator credential;
#                            `retention-check` now says so instead of blaming the
#                            rules.
#   pullfm-restore-drill     DESTROYS DATA on the staging branch and needs a Neon
#                            API key that can delete branches. Monthly drilling is
#                            a Gate 4 obligation, but arming it on a node that has
#                            never run it once unattended is how a drill becomes
#                            an incident. It stays an operator-run script.
#   pullfm-deletion-ledger   Superseded for its original purpose. apps/bff writes
#                            the ledger object inline with the deletion cascade
#                            and refuses the delete if that write fails, so
#                            erasure durability is synchronous with the request
#                            and no longer waits for a ten-minute timer. What is
#                            left is a reconciler, and running it here would mean
#                            putting a SECOND R2 credential - the ledger bucket's,
#                            which is a different token for a different bucket on
#                            purpose - on the node to backfill rows that no longer
#                            accumulate.
#
# All three are recorded in docs/RUNBOOK-DR.md section 6 rather than left to be
# rediscovered.
#
# The units read /etc/pullfm/backup.env, rendered by infra/lib/secrets.sh from
# 1Password and placed root-owned 0600 by converge. There is no `op` on this
# node and there must not be: a scheduled job that needs an interactive vault
# unlock is a scheduled job that does not run.
if [ -d backup ]; then
  # --- the two binaries the dump actually shells out to ---------------------
  #
  # NEITHER IS ON A STOCK UBUNTU 24.04 NODE, and this was the part that made the
  # gap more than a missing `install` line. `pullfm-backup.sh` calls
  # `pullfm_need pg_dump psql python3` and `pullfm_need aws`; python3 and
  # openssl are present, the other two are not, and a unit that dies in
  # `pullfm_need` fails identically to one that has no credentials.
  #
  # pg_dump comes from PGDG rather than from Ubuntu because the major version has
  # to match the server; the reasoning and the version test are in
  # `ensure_pg_client` above, which the canonical loader below shares.
  #
  # The AWS CLI is pinned to an exact version and an exact digest, from the
  # VERSIONED url rather than the moving one. `awscli-exe-linux-x86_64.zip`
  # changes under you, so a hash check against it would fail on the day AWS
  # ships a release and a bootstrap with no hash check would silently install
  # whatever was served. The two urls were confirmed byte-identical on
  # 2026-07-29; the versioned one is the one that stays that way.
  AWSCLI_VERSION=2.36.10
  AWSCLI_SHA256=f6bf7f19f584a1b32b50217f357f2a5877204cf6f703fec8036cd774932383dd

  ensure_pg_client
  install_pg_path_dropin pullfm-backup-dump.service

  if [ "$(aws --version 2>/dev/null | cut -d' ' -f1)" != "aws-cli/${AWSCLI_VERSION}" ]; then
    echo "installing aws-cli ${AWSCLI_VERSION}"
    apt-get install -y -qq unzip curl ca-certificates
    rm -rf /tmp/awscli && install -d -m 0700 /tmp/awscli
    curl -fsSL -o /tmp/awscli/aws.zip \
      "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWSCLI_VERSION}.zip"
    echo "${AWSCLI_SHA256}  /tmp/awscli/aws.zip" | sha256sum -c - || {
      echo "aws-cli archive does not match the pinned digest" >&2
      rm -rf /tmp/awscli
      exit 1
    }
    unzip -q -d /tmp/awscli /tmp/awscli/aws.zip
    # --update so a re-run over an existing install is a no-op rather than an
    # error, which is what makes this whole script safe to re-run.
    /tmp/awscli/aws/install --update >/dev/null
    rm -rf /tmp/awscli
  fi

  # --- the tool itself -------------------------------------------------------
  #
  # /opt/pullfm/infra/... rather than /usr/local/bin, because that is the path
  # the committed units already name in ExecStart and because pullfm-backup.sh
  # computes ROOT as two directories up and sources ../lib/backup-common.sh from
  # it. Flattening it into /usr/local/bin would break that source at the first
  # firing, at 03:23, with nobody watching.
  #
  # ONLY THE DUMP TOOL AND ITS LIBRARY ARE SHIPPED. pullfm-restore.sh and
  # restore-drill.sh stay off the node: nothing installed here executes them,
  # both want a Neon API key that can delete branches, and a restore is run by a
  # person from a checkout. Shipping a tool "in case" is how a node ends up
  # holding the credential for a capability it never uses.
  install -d -m 0755 /opt/pullfm/infra /opt/pullfm/infra/backup /opt/pullfm/infra/lib
  install -m 0755 backup/pullfm-backup.sh /opt/pullfm/infra/backup/pullfm-backup.sh
  install -m 0644 lib/backup-common.sh /opt/pullfm/infra/lib/backup-common.sh

  install -m 0644 backup/systemd/pullfm-backup-dump.service /etc/systemd/system/
  install -m 0644 backup/systemd/pullfm-backup-dump.timer /etc/systemd/system/

  # Remove a retention unit left by an earlier run of this script, which
  # installed it before the AccessDenied above was measured. Leaving it would
  # keep a weekly failing timer on the node with nothing in the repository that
  # explains it, which is the shape of every stale unit anybody has ever found.
  if [ -f /etc/systemd/system/pullfm-backup-retention.timer ]; then
    systemctl disable --now pullfm-backup-retention.timer >/dev/null 2>&1 || true
    rm -f /etc/systemd/system/pullfm-backup-retention.timer \
      /etc/systemd/system/pullfm-backup-retention.service
  fi

  if [ ! -f /etc/pullfm/backup.env ]; then
    echo "WARNING: /etc/pullfm/backup.env is missing. The backup units carry" >&2
    echo "ConditionPathExists for it, so they will SKIP rather than fail - which" >&2
    echo "means no dump and no alert about there being no dump." >&2
  fi
else
  echo "WARNING: backup/ was not shipped; NO SCHEDULED DATABASE BACKUP will be" >&2
  echo "installed on this node. See infra/backup/README.md and PULLFM-RISK-012." >&2
fi

# --- the MusicBrainz canonical refresh --------------------------------------
#
# WHAT WAS WRONG, AND IT IS PULLFM-RISK-012 IN A SECOND PLACE. Enumerated on
# this node on 2026-07-29, hours after the backup timer was armed: eight pullfm
# timers and not one of them the canonical refresh; nothing in
# /etc/systemd/system matching mb-canonical; no /opt/pullfm/infra/mb-loader; and
# `mb.canonical` at 0 rows against a schema migration 0007 had already created.
# An earlier attempt had copied the two units onto the node to run
# `systemd-analyze verify` and then REMOVED THEM AGAIN, so the machine had been
# touched by this work and carried no trace of it. Reading the repository would
# have concluded the refresh was scheduled.
#
# WHY A HOST JOB rather than one of the four container jobs above. The loader is
# `curl -> tee(sha256) -> zstd -dc -> tar -xO -> psql COPY` and needs psql,
# zstd, tar, curl and awk on the machine. The BFF runtime image is
# node:22-alpine plus dumb-init and has none of them, and the loader script is
# not in the image either - the build ships `pnpm deploy --prod /out`, which is
# JavaScript. So `pullfm-job refresh-mb-canonical` would fail on a missing
# binary before reaching anything this repository controls. Same call, same
# reason, as infra/backup/. The full argument is in
# infra/mb-loader/systemd/README.md.
#
# WHY IT MUST RUN HERE AND NOT FROM A WORKSTATION. 2.32 GB in, 31.5M rows out.
# From a residential connection: 0.5 MB/s, upload bound, about 5.5 hours. From
# this node: minutes. The timer exists because the node is the correct host.
#
# The unit reads /etc/pullfm/mb-canonical.env, rendered by infra/lib/secrets.sh
# from 1Password and placed root-owned 0600 by converge. It carries the OWNER
# DSN, which can DROP the live table, and that is why it is a separate file from
# bff.env rather than more lines in it: bff.env is bind-mounted into the
# internet-facing container.
if [ -d mb-loader ]; then
  # psql only. `pg_dump` is not called by the loader, but the version test in
  # `ensure_pg_client` keys off it because the two ship from one package, and a
  # node converged with mb-loader and without backup still needs a client that
  # matches the server rather than whichever one pg_wrapper picks.
  ensure_pg_client
  install_pg_path_dropin pullfm-mb-canonical.service

  # /opt/pullfm/infra/... because that is the path the committed unit already
  # names in ExecStart. ONLY THE LOADER. selftest.sh stays off the node: it wants
  # a local docker Postgres from `stack:up` and exits 77 without one, and nothing
  # installed here executes it. Shipping a tool "in case" is how a node ends up
  # holding a capability it never uses.
  #
  # No `lib` dependency, unlike pullfm-backup.sh: the loader sources nothing and
  # computes no ROOT, so the script alone is the whole install.
  install -d -m 0755 /opt/pullfm/infra /opt/pullfm/infra/mb-loader
  install -m 0755 mb-loader/mb-canonical-load.sh /opt/pullfm/infra/mb-loader/mb-canonical-load.sh

  install -m 0644 mb-loader/systemd/pullfm-mb-canonical.service /etc/systemd/system/
  install -m 0644 mb-loader/systemd/pullfm-mb-canonical.timer /etc/systemd/system/

  # LOUDER THAN THE BACKUP'S EQUIVALENT WARNING, ON PURPOSE. Both units carry
  # ConditionPathExists, so both SKIP rather than fail when their env file is
  # absent - but a skipped backup is a gap somebody notices the first time they
  # look in the bucket, and a skipped canonical load is invisible: the table is
  # empty, `MB_LOCAL_ENABLED` defaults to false, and every cold lookup returns
  # nothing exactly as it did before the pipeline existed.
  if [ ! -f /etc/pullfm/mb-canonical.env ]; then
    echo "WARNING: /etc/pullfm/mb-canonical.env is missing. pullfm-mb-canonical" >&2
    echo "carries ConditionPathExists for it, so the timer will show a real NEXT," >&2
    echo "SKIP every firing, reach OnFailure never, and load nothing. Render it" >&2
    echo "with converge (infra/lib/secrets.sh), never by hand: a hand-edited copy" >&2
    echo "is overwritten by the next converge and the failure is silent." >&2
  fi
else
  echo "WARNING: mb-loader/ was not shipped; NO SCHEDULED MUSICBRAINZ CANONICAL" >&2
  echo "REFRESH will be installed on this node, so mb.canonical will go stale or" >&2
  echo "stay empty. See infra/mb-loader/systemd/README.md." >&2
fi

# --- notification channel and watchdog -------------------------------------
# Shipped from infra/observability/, which converge places alongside this
# directory as ./observability. The alert sender is installed even when
# alert.env is absent: the four job units above name pullfm-job-alert@ in their
# OnFailure, and a missing /usr/local/bin/pullfm-alert would turn a job failure
# into a second, more confusing failure of the thing meant to report it.
#
# The watchdog is what turns a metric CONDITION into a notification, so without
# it the four timers can only report their own exit codes and nothing reports a
# limiter that stopped pacing or a container that stopped answering.
if [ -d observability ]; then
  install -m 0755 observability/pullfm-alert /usr/local/bin/pullfm-alert
  install -m 0755 observability/pullfm-watchdog /usr/local/bin/pullfm-watchdog
  install -m 0644 observability/systemd/pullfm-watchdog.service /etc/systemd/system/
  install -m 0644 observability/systemd/pullfm-watchdog.timer /etc/systemd/system/
  # ReadWritePaths= in the watchdog unit names both of these, and a unit whose
  # ReadWritePaths does not exist fails to start rather than creating it.
  install -d -m 0755 /var/lib/pullfm /var/log/pullfm

  # Points the watchdog at the BFF's own port and gives it the scrape token.
  # A drop-in rather than an edit to the shipped unit: the unit describes what
  # the watchdog does and belongs to infra/observability, while which port
  # answers and which credential opens it are facts about this node's shape.
  # `-` on the EnvironmentFile so an unarmed node still runs the watchdog.
  install -d -m 0755 /etc/systemd/system/pullfm-watchdog.service.d
  cat >/etc/systemd/system/pullfm-watchdog.service.d/10-pullfm-metrics.conf <<'DROPIN'
# Generated by bootstrap.sh. Do not edit.
[Service]
EnvironmentFile=-/etc/pullfm/metrics.env
DROPIN
  chmod 0644 /etc/systemd/system/pullfm-watchdog.service.d/10-pullfm-metrics.conf
else
  echo "WARNING: observability/ was not shipped; no watchdog will be installed" >&2
fi

systemctl daemon-reload
systemctl enable --now pullfm-cf-ranges.timer
systemctl enable --now pullfm-deploy.timer

if [ -x /usr/local/bin/pullfm-watchdog ]; then
  systemctl enable --now pullfm-watchdog.timer
fi

# `enable --now` on a timer, never on the .service. Starting the service here
# would run every job once during bootstrap, before the first deploy has put an
# image on the node, which is the case ConditionPathExists is there to skip.
systemctl enable --now pullfm-warm-cache.timer
systemctl enable --now pullfm-sweep-expired.timer
systemctl enable --now pullfm-purge-audit.timer
systemctl enable --now pullfm-reap-unverified.timer

# THE TIMER, NOT THE UNIT, AND THIS IS THE WHOLE POINT OF PULLFM-RISK-012.
# A unit file that is installed and whose timer is not enabled looks like a
# working control in a diff, in a file listing and in `ls /etc/systemd/system`,
# and produces exactly as many backups as no unit at all. `enable --now` is what
# makes `systemctl list-timers` show a NEXT, and a NEXT is the only evidence
# that anything is scheduled.
if [ -f /etc/systemd/system/pullfm-backup-dump.timer ]; then
  systemctl enable --now pullfm-backup-dump.timer
fi

# Same rule, same reason, for the canonical refresh. `enable --now` on the TIMER
# and never on the .service: starting the service here would pull 2.32 GB during
# a bootstrap and hold it for four minutes on a 3-vCPU node that is at that
# moment also building nginx's config and starting containers.
if [ -f /etc/systemd/system/pullfm-mb-canonical.timer ]; then
  systemctl enable --now pullfm-mb-canonical.timer
fi

echo
echo "bootstrap complete. First deploy runs within 60 seconds, or force it with:"
echo "  systemctl start pullfm-deploy.service && journalctl -u pullfm-deploy -n 50"
echo
echo "scheduled jobs (they skip until the first deploy pins an image):"
echo "  systemctl list-timers 'pullfm-*'"
