#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bootstraps the two shared Redis instances.
#
# THIS USED TO BOOTSTRAP POSTGRES. The database is Neon now (infra/neon), so
# what this places is Redis and nothing else. Nothing about the Redis half
# changed; the Postgres half was deleted rather than rewritten.
#
# IT NO LONGER ASSUMES A DEDICATED NODE. Pre-launch there is one application
# node and no cache node, and Redis runs on the application node. PRIVATE_IP is
# what makes the difference and it is not cosmetic: it is the address the
# containers publish on, and it must be an address that is reachable from
# another container on the node and unreachable from the internet.
#
#   PRIVATE_IP=10.20.1.11  co-located on the application node (default shape):
#                          that node's OWN private address
#   PRIVATE_IP=10.20.1.21  the separate cache node, which is required before
#                          app_node_count can go above one; see
#                          infra/terraform/modules/compute/variables.tf
#
# NOT 127.0.0.1, AND THIS IS THE ONE THAT LOOKS RIGHT AND IS NOT. The loopback
# is the obvious answer for a service that must not leave the node, and it works
# for anything running on the host - but the BFF runs under Compose on a bridge
# network, where 127.0.0.1 is its own namespace and not the host's. Redis
# published there is invisible to it. The private address keeps the property the
# loopback was chosen for (the public interface never carries Redis) while being
# an address a sibling container can actually dial.
#
# infra/staging-env.sh passes it from the terraform output rather than letting
# it default, so the two cannot disagree.
#
# Idempotent: safe to re-run. Run as root ON THE NODE, with the repository's
# infra/staging/cache directory present in the working directory and
# /etc/pullfm/cache.env already placed (it holds the secrets and is never in
# git).
#
#   sudo PRIVATE_IP=10.20.1.11 bash bootstrap.sh       # on the app node
#   ssh -J pullfm@<app-public-ip> pullfm@10.20.1.21    # on a cache node
#   sudo PRIVATE_IP=10.20.1.21 bash bootstrap.sh
#
# A dedicated cache node has no public IPv4 by design, so every package and
# image comes in over IPv6. Docker Hub and the Ubuntu archive were both verified
# reachable over IPv6 from there; if that ever stops being true the fallback is
# `docker save | ssh | docker load` from the application node across the private
# network.
# ---------------------------------------------------------------------------
set -euo pipefail

# NO DEFAULT. Every candidate default is wrong somewhere: the loopback is
# unreachable from the BFF's bridge network, the cache node's address does not
# exist in the co-located shape, and the application node's address does not
# exist on a cache node. infra/staging-env.sh passes the value from the
# `redis_host` terraform output, which is the only place it is decided, so a
# missing one is a caller bug and should stop here rather than bind somewhere
# plausible and wrong.
PRIVATE_IP=${PRIVATE_IP:?PRIVATE_IP is required: pass the redis_host terraform output}
ENV_FILE=/etc/pullfm/cache.env

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root" >&2
  exit 1
fi

if [ ! -f "${ENV_FILE}" ]; then
  echo "${ENV_FILE} is missing. Place it first; it holds REDIS_CACHE_PASSWORD" >&2
  echo "and REDIS_QUOTA_PASSWORD from 1Password." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a && . "${ENV_FILE}" && set +a

# --- packages --------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
# Ubuntu's own packages rather than Docker's apt repository: one fewer third
# party signing key trusted on a node that holds every user credential.
# postgresql-client is no longer installed here. It was for poking at the local
# cluster, and there is no local cluster; a psql session against Neon runs from
# the operator's laptop over TLS, not from a node.
apt-get install -y -qq docker.io docker-compose-v2

systemctl enable --now docker

# --- redis configuration ---------------------------------------------------
# Rendered here rather than shipped in git, because both files carry a
# password. Bind is 0.0.0.0 inside the container's own namespace; the exposure
# boundary is the compose port binding to the private address.
# The redis image drops to uid 999 (whose group id is NOT 999 - the official
# image uses gid 1000), so ownership is set by uid and the group bits are left
# with nothing to grant. /etc/pullfm itself stays unlistable; only the traverse
# bit is opened, and the two files below carry a password so nothing but root
# and that one uid may read them.
install -d -m 0751 /etc/pullfm
install -d -m 0700 -o 999 /etc/pullfm/redis

cat >/etc/pullfm/redis/cache.conf <<EOF
# Pull.fm staging cache. Generated by bootstrap.sh; do not edit by hand.
port 6379
protected-mode yes
requirepass ${REDIS_CACHE_PASSWORD:?REDIS_CACHE_PASSWORD is required}
# Evictable on purpose. Losing a key here is a cache miss and nothing more.
maxmemory 256mb
maxmemory-policy allkeys-lru
# No persistence: a cache that survives a restart is a cache serving answers
# from before whatever caused the restart.
save ""
appendonly no
EOF

cat >/etc/pullfm/redis/quota.conf <<EOF
# Pull.fm staging quota and rate-limit counters.
# Generated by bootstrap.sh; do not edit by hand.
port 6379
protected-mode yes
requirepass ${REDIS_QUOTA_PASSWORD:?REDIS_QUOTA_PASSWORD is required}
maxmemory 128mb
# noeviction is the entire reason this is a second instance. Under allkeys-lru
# a cache-fill event silently evicts rate-limit counters, every limit then
# fails OPEN, and nothing logs or alerts. See THREAT-MODEL T11.
maxmemory-policy noeviction
# Counters are cheap to lose but expensive to lose silently mid-window, so a
# light AOF is kept. This is not a durability guarantee, it is a restart hint.
appendonly yes
appendfsync everysec
EOF

chown 999 /etc/pullfm/redis/cache.conf /etc/pullfm/redis/quota.conf
chmod 0600 /etc/pullfm/redis/cache.conf /etc/pullfm/redis/quota.conf

# --- compose ---------------------------------------------------------------
install -d -m 0755 /opt/pullfm-cache
install -m 0644 docker-compose.yml /opt/pullfm-cache/docker-compose.yml

# Rewritten rather than appended-if-absent. This value now varies between the
# two supported shapes, so a stale line left over from a previous converge would
# silently keep Redis bound where it used to be.
sed -i '/^PRIVATE_IP=/d' "${ENV_FILE}"
printf 'PRIVATE_IP=%s\n' "${PRIVATE_IP}" >>"${ENV_FILE}"
chmod 0600 "${ENV_FILE}"

# --- the address has to exist before anything binds to it -------------------
#
# WHAT WAS WRONG. A rebuild in ash on 2026-07-29 came up with the Hetzner
# private NIC present, DOWN and configured nowhere, because cloud-init read the
# metadata service before Hetzner attached the private network. `docker compose
# up` then died with "failed to bind host port 10.20.1.11:6379: cannot assign
# requested address", converge stopped at its last step, and the BFF failed
# closed on its rate limiter and refused all traffic.
#
# WHY THIS SHAPE. The bind failure names the address but not the reason, so it
# reads as a compose or a docker problem for as long as it takes somebody to run
# `ip addr`. Asserting first turns the same fault into one line that says which
# address is missing and where the repair lives. /usr/local/sbin/pullfm-private-net
# is installed by cloud-init (see the compute module's template) and is the one
# place that knows how to re-derive the interface from the metadata service; this
# calls it rather than carrying a second copy of that logic, and still refuses to
# continue if it did not help.
assert_private_ip() {
  ip -4 -o addr show 2>/dev/null | grep -qFw -- "${PRIVATE_IP}"
}

if ! assert_private_ip; then
  echo "${PRIVATE_IP} is not assigned to any interface on this node." >&2
  if [ -x /usr/local/sbin/pullfm-private-net ]; then
    echo "re-deriving the private interface from the metadata service" >&2
    /usr/local/sbin/pullfm-private-net 60 || true
  fi
fi

if ! assert_private_ip; then
  echo >&2
  echo "REFUSING TO START REDIS: ${PRIVATE_IP} is not assigned to any" >&2
  echo "interface on this node, so every published port would fail to bind." >&2
  echo >&2
  ip -4 -br addr >&2 || true
  echo >&2
  echo "Hetzner attaches the private network AFTER boot, so cloud-init can" >&2
  echo "render its network config without it. See:" >&2
  echo "  /var/lib/pullfm/private-net-FAILED" >&2
  echo "  journalctl -t pullfm-private-net" >&2
  echo "  /usr/local/sbin/pullfm-private-net   (re-runs the repair)" >&2
  exit 1
fi

cd /opt/pullfm-cache
docker compose --env-file "${ENV_FILE}" up -d

# --- a container that failed to bind must not be left looking healthy --------
#
# WHAT WAS WRONG, and it is the second half of the same incident. Once the
# interface was up, the Redis containers still had NO PUBLISHED PORTS, because
# they had been CREATED during the converge in which the bind was impossible and
# the retry above merely STARTED the containers that already existed. `docker ps`
# reported both `healthy` throughout, and it was telling the truth about the only
# thing it was asked: the compose healthcheck runs `redis-cli ping` INSIDE the
# container, over the container's own loopback, and says nothing whatsoever about
# whether a host port exists. The BFF, which reaches Redis from a different
# network namespace, saw nothing. Recovery was `docker compose down && up`.
#
# WHY THIS SHAPE, AND NOT `up -d --force-recreate` UNCONDITIONALLY. Recreating
# on every converge would be simpler and it would restart the QUOTA instance
# every time, which is live rate-limit and quota state; the BFF fails closed on
# its limiter, so each converge would buy a window of refused traffic to fix a
# fault that is not usually present. So the binding is CHECKED and the recreate
# is the remedy, not the routine. `--force-recreate` rather than `down`: it
# discards exactly the wrong thing (the container) without removing the compose
# network or going anywhere near the redisquota volume.
#
# WHY IT IS CHECKED TWICE, in two different ways. `docker ps` proves docker
# believes it published the port; a TCP connect proves something is listening on
# that address for real. The first can be true while the second is false, and it
# is the second that the BFF depends on.
published_ok() {
  local svc port cid ports
  for svc in redis-cache:6379 redis-quota:6380; do
    port="${svc##*:}"
    svc="${svc%%:*}"
    cid="$(docker compose --env-file "${ENV_FILE}" ps -q "${svc}" 2>/dev/null)"
    [ -n "${cid}" ] || return 1
    ports="$(docker ps --no-trunc --filter "id=${cid}" --format '{{.Ports}}')"
    printf '%s' "${ports}" | grep -qF -- "${PRIVATE_IP}:${port}->" || return 1
  done
}

if ! published_ok; then
  echo >&2
  echo "the redis containers are not publishing ${PRIVATE_IP}:6379 and :6380;" >&2
  echo "recreating them rather than starting the containers that failed to bind" >&2
  docker ps --format '  {{.Names}}  {{.Status}}  [{{.Ports}}]' >&2 || true
  docker compose --env-file "${ENV_FILE}" up -d --force-recreate
fi

if ! published_ok; then
  echo >&2
  echo "REDIS IS NOT PUBLISHED ON ${PRIVATE_IP}:6379 and :6380 after a forced" >&2
  echo "recreate. The BFF reaches Redis from another network namespace, so it" >&2
  echo "would come up and fail closed on its rate limiter." >&2
  docker ps --format '  {{.Names}}  {{.Status}}  [{{.Ports}}]' >&2 || true
  docker compose --env-file "${ENV_FILE}" logs --tail 30 >&2 || true
  exit 1
fi

echo
echo "waiting for redis"
for _ in $(seq 1 30); do
  # NOAUTH proves the server is up AND enforcing authentication, so it is a
  # success here for the same reason it is in the compose healthchecks.
  if docker compose --env-file "${ENV_FILE}" exec -T redis-cache \
    redis-cli ping 2>&1 | grep -qE 'PONG|NOAUTH'; then
    echo "redis is ready"
    break
  fi
  sleep 2
done

# The proof that is worth having, from OUTSIDE the containers: a TCP connect to
# the published address, which is the thing the BFF actually does and the thing
# every check above this line was unable to see.
for port in 6379 6380; do
  if timeout 3 bash -c "</dev/tcp/${PRIVATE_IP}/${port}" 2>/dev/null; then
    echo "  ${PRIVATE_IP}:${port} accepts connections"
  else
    echo "nothing is listening on ${PRIVATE_IP}:${port}" >&2
    exit 1
  fi
done

docker compose --env-file "${ENV_FILE}" ps
