#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bootstraps the Pull.fm staging database node.
#
# Idempotent: safe to re-run. Run as root ON THE NODE, with the repository's
# infra/staging/db directory present in the working directory and
# /etc/pullfm/db.env already placed (it holds the secrets and is never in git).
#
#   ssh -J pullfm@<app-public-ip> pullfm@10.20.1.21
#   sudo bash bootstrap.sh
#
# This node has no public IPv4 by design, so every package and image comes in
# over IPv6. Docker Hub, the Ubuntu archive and the PGDG mirror were all
# verified reachable over IPv6 from here before this was written down; if that
# ever stops being true the fallback is `docker save | ssh | docker load` from
# the application node across the private network.
# ---------------------------------------------------------------------------
set -euo pipefail

PRIVATE_IP=${PRIVATE_IP:-10.20.1.21}
ENV_FILE=/etc/pullfm/db.env

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root" >&2
  exit 1
fi

if [ ! -f "${ENV_FILE}" ]; then
  echo "${ENV_FILE} is missing. Place it first; it holds POSTGRES_PASSWORD," >&2
  echo "REDIS_CACHE_PASSWORD and REDIS_QUOTA_PASSWORD from 1Password." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a && . "${ENV_FILE}" && set +a

# --- packages --------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
# Ubuntu's own packages rather than Docker's apt repository: one fewer third
# party signing key trusted on a node that holds every user credential.
apt-get install -y -qq docker.io docker-compose-v2 postgresql-client-16

systemctl enable --now docker

# --- redis configuration ---------------------------------------------------
# Rendered here rather than shipped in git, because both files carry a
# password. Bind is 0.0.0.0 inside the container's own namespace; the exposure
# boundary is the compose port binding to the private address.
# The redis image drops to uid 999 (whose group id is NOT 999 - the official
# image uses gid 1000), so ownership is set by uid and the group bits are left
# with nothing to grant. /etc/pullfm itself stays unlistable; only the traverse
# bit is opened, and the two files below carry a password so nothing but root
# and that one uid may read them.
install -d -m 0751 /etc/pullfm
install -d -m 0700 -o 999 /etc/pullfm/redis

cat >/etc/pullfm/redis/cache.conf <<EOF
# Pull.fm staging cache. Generated by bootstrap.sh; do not edit by hand.
port 6379
protected-mode yes
requirepass ${REDIS_CACHE_PASSWORD:?REDIS_CACHE_PASSWORD is required}
# Evictable on purpose. Losing a key here is a cache miss and nothing more.
maxmemory 256mb
maxmemory-policy allkeys-lru
# No persistence: a cache that survives a restart is a cache serving answers
# from before whatever caused the restart.
save ""
appendonly no
EOF

cat >/etc/pullfm/redis/quota.conf <<EOF
# Pull.fm staging quota and rate-limit counters.
# Generated by bootstrap.sh; do not edit by hand.
port 6379
protected-mode yes
requirepass ${REDIS_QUOTA_PASSWORD:?REDIS_QUOTA_PASSWORD is required}
maxmemory 128mb
# noeviction is the entire reason this is a second instance. Under allkeys-lru
# a cache-fill event silently evicts rate-limit counters, every limit then
# fails OPEN, and nothing logs or alerts. See THREAT-MODEL T11.
maxmemory-policy noeviction
# Counters are cheap to lose but expensive to lose silently mid-window, so a
# light AOF is kept. This is not a durability guarantee, it is a restart hint.
appendonly yes
appendfsync everysec
EOF

chown 999 /etc/pullfm/redis/cache.conf /etc/pullfm/redis/quota.conf
chmod 0600 /etc/pullfm/redis/cache.conf /etc/pullfm/redis/quota.conf

# --- compose ---------------------------------------------------------------
install -d -m 0755 /opt/pullfm-db
install -m 0644 docker-compose.yml /opt/pullfm-db/docker-compose.yml

grep -q '^PRIVATE_IP=' "${ENV_FILE}" || printf 'PRIVATE_IP=%s\n' "${PRIVATE_IP}" >>"${ENV_FILE}"
chmod 0600 "${ENV_FILE}"

cd /opt/pullfm-db
docker compose --env-file "${ENV_FILE}" up -d

echo
echo "waiting for postgres"
for _ in $(seq 1 60); do
  if docker compose --env-file "${ENV_FILE}" exec -T postgres pg_isready -U pullfm -d pullfm >/dev/null 2>&1; then
    echo "postgres is ready"
    break
  fi
  sleep 2
done

docker compose --env-file "${ENV_FILE}" ps
