#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Pull.fm - produce a DAST-SAFE OpenAPI document for ZAP
//
// WHY THIS EXISTS
//
// ZAP's `openapi` import job sends a request for every operation it finds, in
// order to seed the sites tree. Handed the real spec, that means ZAP issues
// DELETE /v1/me and DELETE /v1/connections/{service} during import, destroying
// the scan subject before a single alert is raised. The rest of the run then
// produces 401s and a clean report, which is the worst possible outcome: a
// green DAST result that proves nothing.
//
// ZAP context exclusions cannot fix this. They are URL-scoped, not
// method-scoped, so excluding `/v1/me` to protect DELETE would also hide GET
// /v1/me, which is the plan's authentication sanity check. Method-level control
// has to happen before ZAP sees the document, which is what this script does.
//
// It removes every operation annotated `x-pullfm-dast: "exclude"` and FAILS if
// any operation carries no annotation at all. Failing closed is the point: the
// alternative default, "include unless told otherwise", means the first
// destructive route someone adds without thinking gets scanned.
//
// Usage:
//   node security/zap/scripts/prune-openapi.mjs <in.json> <out.json> [--quiet]
// Exit: 0 written, 1 an operation is unannotated, 2 usage or IO error.
// ---------------------------------------------------------------------------

import { writeFileSync } from "node:fs";
import {
  loadSpec,
  eachOperation,
  routeKey,
  SpecError,
  HTTP_METHODS,
} from "../../lib/openapi.mjs";

const DISPOSITIONS = new Set(["include", "exclude"]);

export function prune(doc) {
  const problems = [];
  const kept = [];
  const removed = [];

  for (const op of eachOperation(doc)) {
    const disposition = op.operation["x-pullfm-dast"];
    if (!DISPOSITIONS.has(disposition)) {
      problems.push({
        route: routeKey(op),
        message:
          `x-pullfm-dast is ${JSON.stringify(disposition)}; must be "include" or "exclude". ` +
          "Unannotated operations are rejected rather than defaulted, because the default that " +
          "would be convenient here is the one that lets a destructive route be scanned.",
      });
      continue;
    }
    (disposition === "include" ? kept : removed).push(routeKey(op));
  }

  if (problems.length > 0) return { problems, kept, removed, doc: null };

  // structuredClone keeps the original untouched, which matters because the
  // caller may be a test asserting the input was not mutated.
  const out = structuredClone(doc);
  out.info = { ...out.info };
  out.info.title = `${out.info.title ?? "API"} (DAST-safe subset)`;
  out.info["x-pullfm-dast-pruned"] = {
    removedOperations: removed,
    note:
      "Generated by security/zap/scripts/prune-openapi.mjs. Operations annotated " +
      "x-pullfm-dast: exclude are absent. Do not use this document for anything except DAST.",
  };

  // Rebuilt rather than mutated in place: an allowlist ("keep these entries")
  // cannot accidentally retain an operation the way a denylist ("delete these
  // keys") can if a method name is missed. For a filter whose job is to stop a
  // destructive route reaching the scanner, the direction of the default
  // matters more than the line count.
  out.paths = Object.fromEntries(
    Object.entries(out.paths)
      .map(([path, item]) => {
        const surviving = Object.fromEntries(
          Object.entries(item).filter(
            ([key, value]) =>
              !HTTP_METHODS.includes(key) ||
              value?.["x-pullfm-dast"] !== "exclude",
          ),
        );
        return [path, surviving];
      })
      // A path item left holding only `parameters` would make ZAP request the
      // bare path, which is not an operation the API declares.
      .filter(([, item]) => HTTP_METHODS.some((m) => item[m])),
  );

  return { problems, kept, removed, doc: out };
}

function main() {
  const argv = process.argv.slice(2);
  const quiet = argv.includes("--quiet");
  const positional = argv.filter((a) => !a.startsWith("--"));
  if (argv.includes("--help") || positional.length !== 2) {
    process.stderr.write(
      "Usage: node security/zap/scripts/prune-openapi.mjs <in.json> <out.json> [--quiet]\n",
    );
    process.exit(2);
  }
  const [input, output] = positional;

  let doc;
  try {
    doc = loadSpec(input);
  } catch (err) {
    if (err instanceof SpecError) {
      process.stderr.write(`${err.message}\n`);
      process.exit(2);
    }
    throw err;
  }

  let result;
  try {
    result = prune(doc);
  } catch (err) {
    if (err instanceof SpecError) {
      process.stderr.write(`${err.message}\n`);
      process.exit(1);
    }
    throw err;
  }

  if (result.problems.length > 0) {
    for (const p of result.problems) {
      process.stderr.write(`UNANNOTATED  ${p.route}: ${p.message}\n`);
    }
    process.stderr.write(
      `\nFAIL    ${result.problems.length} operation(s) have no DAST disposition. ` +
        'Add `"x-pullfm-dast": "include"` or `"exclude"` to each.\n',
    );
    process.exit(1);
  }

  try {
    writeFileSync(output, `${JSON.stringify(result.doc, null, 2)}\n`);
  } catch (err) {
    process.stderr.write(`cannot write ${output}: ${err.message}\n`);
    process.exit(2);
  }

  if (!quiet) {
    process.stdout.write(
      `OK      ${result.kept.length} operation(s) in the DAST-safe spec, ` +
        `${result.removed.length} excluded -> ${output}\n`,
    );
    for (const r of result.removed)
      process.stdout.write(`        excluded: ${r}\n`);
  }
  process.exit(0);
}

if (process.argv[1] && process.argv[1].endsWith("prune-openapi.mjs")) main();
