/**
 * The product surface, implemented.
 *
 * `packages/discovery` owns the ranking and knows nothing about HTTP or about
 * caching. This file is the adapter between the two: it implements
 * `DiscoveryPorts` over `CachedUpstream`, so the blend cannot reach a provider
 * even by mistake, and it turns the resulting `SectionsEnvelope` into the wire
 * shape the OpenAPI document already published.
 *
 * WHAT IS SYNCHRONOUS AND WHAT IS NOT
 * -----------------------------------
 * See services/upstream.ts for the per-provider argument. The consequences
 * visible in this file:
 *
 *   - Every ListenBrainz and Last.fm read is `cache.fetch`, a read-through
 *     with a TTL. Their budgets are per-token and per-app-key respectively,
 *     which are budgets a single request may legitimately spend.
 *   - Every MusicBrainz read is `cache.peek`, which never calls out. A miss is
 *     a missing name, not a lookup. That is what `hydrateRecordings` returning
 *     a partial map is for, and why `made_for_you` can be empty on a cold cache
 *     while every other shelf still renders.
 *   - Preview reads come from `track_previews` (iTunes, persistable) and, only
 *     when that misses, from a live Deezer resolve whose result is deliberately
 *     thrown away after it is returned once.
 *
 * DEGRADATION IS THE CONTRACT, NOT AN ERROR PATH
 * ----------------------------------------------
 * A dead provider removes one shelf and sets `degraded`. `buildFeed` already
 * does this and the adapter must not undo it, so every port method converts an
 * upstream degradation into an empty result or a throw that `buildFeed` catches
 * per-section, never into a rejection that escapes to the route.
 *
 * CREDENTIALS
 * -----------
 * `#listenBrainzPort` receives the plaintext token as a closure argument and
 * passes it straight to the client. It is never assigned to the request, the
 * reply, a cache key, an error, or a log line. `.semgrep/pullfm.yml` enforces
 * the first and last of those mechanically.
 */

import {
  LASTFM_ATTRIBUTION,
  artistUrl,
  isUpstreamError,
  normalizeKey,
  normalizeTitle,
  trackUrl,
  type CrosswalkHit,
  type MusicBrainzArtist,
  type MusicBrainzRecording,
  type MusicBrainzRelease,
  type PreviewAttribution,
} from "@pull-fm/upstream";
import {
  buildFeed,
  type Attribution,
  type ArtistListenRef,
  type DiscoveryPorts,
  type FeedSection,
  type LastfmPort,
  type ListenBrainzPort,
  type PlaylistRef,
  type RadioTrackRef,
  type RecordingRecommendationRef,
  type SectionsEnvelope,
  type SimilarArtistRef,
  type SimilarTrackRef,
  type TrackRef,
} from "@pull-fm/discovery";

import { errors } from "../lib/errors.js";
import { decodeCursor, encodeCursor } from "../lib/cursor.js";
import type { SigningKeys } from "../lib/keys.js";
import {
  CanonicalArtistLookupGate,
  type ArtistLookupGate,
} from "./artist-lookup-gate.js";
import type { ConnectionService } from "./connections.js";
import type { UpstreamBundle } from "./upstream.js";

// ---------------------------------------------------------------------------
// Cache keys and TTLs.
//
// TTLs are chosen against how fast the answer changes, EXCEPT where a licence
// says otherwise. Last.fm's is long because their 100 MB cap (ToS 4.3.4) is
// relieved by fewer, longer-lived rows, not by more of them.
// ---------------------------------------------------------------------------
const TTL = {
  /** Regenerated by ListenBrainz on a multi-day cadence. */
  recommendations: 6 * 60 * 60,
  /** Listening statistics move slowly and a stale hour is invisible. */
  topArtists: 6 * 60 * 60,
  /** Artist radio is derived from a similarity model, not from activity. */
  artistRadio: 24 * 60 * 60,
  /** Weekly Jams / Weekly Discovery are rewritten weekly. */
  playlists: 60 * 60,
  /** labs.api has no SLA; a long TTL is what makes it survivable. */
  labsSimilar: 7 * 24 * 60 * 60,
  /** Last.fm: long by licence, not by volatility. */
  lastfm: 7 * 24 * 60 * 60,
  /**
   * MusicBrainz core data. CC0, with no cache cap and no storage limit, so this
   * is bounded only by how often a title is corrected or an MBID merged.
   */
  musicbrainz: 30 * 24 * 60 * 60,
} as const;

/**
 * Sections per feed page.
 *
 * Small enough that a first render is cheap on a phone, and large enough that
 * the common case is a single page. The cursor is what makes this changeable
 * without a client release.
 */
const SECTIONS_PER_PAGE = 4;

/** Trigram floor for `GET /v1/search`. Below this the results are noise. */
const SEARCH_MIN_SIMILARITY = 0.25;

// ---------------------------------------------------------------------------
// Wire shapes for the catalogue routes.
// ---------------------------------------------------------------------------

export interface ArtistView {
  readonly mbid: string;
  readonly name: string;
  readonly sortName: string | null;
  readonly country: string | null;
  readonly beganYear: number | null;
  // There is deliberately NO `tags` field, and the absence is a decision.
  // MusicBrainz core data is CC0 and carries no obligations. Tags, genres and
  // ratings are SUPPLEMENTARY data under CC BY-NC-SA 3.0, so surfacing them
  // would attach attribution, NonCommercial and ShareAlike terms to this
  // response and to everything derived from it - including, fatally, anything
  // a personal API token consumer builds on top. The client stopped requesting
  // them entirely (docs/compliance/metabrainz-terms-review.md F1).
  /** Where the record came from, so a thin answer is legible as a thin answer. */
  readonly resolution: "musicbrainz" | "crosswalk";
  readonly attribution: readonly Attribution[];
}

export interface TrackView {
  readonly mbid: string;
  readonly title: string;
  readonly artistName: string;
  readonly artistMbid: string | null;
  readonly durationMs: number | null;
  readonly resolution: "musicbrainz";
  readonly attribution: readonly Attribution[];
}

export interface AlbumView {
  readonly mbid: string;
  readonly title: string;
  readonly artistName: string;
  readonly artistMbid: string | null;
  readonly date: string | null;
  readonly country: string | null;
  readonly trackCount: number | null;
  readonly resolution: "musicbrainz";
  readonly attribution: readonly Attribution[];
}

export interface PreviewView {
  readonly recordingMbid: string;
  readonly provider: "itunes" | "deezer";
  readonly url: string;
  readonly durationMs: number | null;
  /**
   * What the client MUST render alongside the preview.
   *
   * A string was enough while the only obligation was Apple's exact
   * "provided courtesy of iTunes" phrase. It is not enough for their condition
   * (ii), which requires the preview to sit next to an approved store badge
   * linking to the page where THIS track can be purchased. The badge and its
   * per-item link therefore travel with the URL, in the same object, so a
   * client cannot receive something playable without also receiving what it is
   * obliged to display next to it.
   */
  readonly attribution: PreviewAttribution;
  /**
   * Epoch milliseconds at which the URL stops working, or null when it does
   * not expire. Deezer signs its URLs; iTunes does not.
   */
  readonly expiresAt: number | null;
  /**
   * False for Deezer. A client that caches a `false` URL will serve a 403 to
   * its user minutes later, which is why the flag is on the wire rather than
   * being something the client is expected to infer from `provider`.
   */
  readonly cacheable: boolean;
}

export interface DiscoveryOptions {
  readonly limit?: number | undefined;
  readonly cursor?: string | undefined;
}

const CURSOR_SCOPE_FEED = "feed";

/**
 * Credit carried by anything sourced from MusicBrainz.
 *
 * Unlike Last.fm's, this is COURTESY rather than a licence condition: core
 * MusicBrainz data is CC0, which imposes no attribution requirement at all
 * (docs/compliance/metabrainz-terms-review.md). It is emitted anyway because a
 * client rendering a mixed shelf has to be able to say where each item came
 * from, and because the moment supplementary data were ever added the
 * obligation would become real - at which point the field already exists and
 * the change is the licence URI rather than a new contract.
 */
const MUSICBRAINZ_ATTRIBUTION: Attribution = {
  source: "musicbrainz",
  text: "Metadata from MusicBrainz",
  url: "https://musicbrainz.org",
};

export class DiscoveryService {
  readonly #upstream: UpstreamBundle;
  readonly #connections: ConnectionService;
  readonly #keys: SigningKeys;
  /**
   * Decides whether an artist MBID is worth an upstream similarity call.
   *
   * Constructed here rather than injected because its two local probes are
   * private to this class, and because there is exactly one correct wiring of
   * it: a gate that consulted a different cache from the one the lookup uses
   * would decline calls whose answers were already warm.
   */
  readonly #artistGate: ArtistLookupGate;

  constructor(
    upstream: UpstreamBundle,
    connections: ConnectionService,
    keys: SigningKeys,
  ) {
    this.#upstream = upstream;
    this.#connections = connections;
    this.#keys = keys;
    this.#artistGate = new CanonicalArtistLookupGate({
      canonical: upstream.canonical,
      // "Anything this product has already resolved or learned." Both probes
      // are indexed single-row reads, and both are the SAME reads the lookup
      // itself would perform, so a warm artist can never be declined.
      knownLocally: async (mbid) => {
        if ((await this.#peekArtist(mbid)) !== null) return true;
        return (await this.#nameFromCrosswalk("artist", mbid)) !== null;
      },
    });
  }

  // -------------------------------------------------------------------------
  // Feed and recommendations
  // -------------------------------------------------------------------------

  /**
   * The personalised feed.
   *
   * Paged over SECTIONS rather than over items, because a section is the unit
   * the client renders and the unit whose cost is bounded. Item-level paging
   * across a blended feed would require a stable global ordering that a blend
   * of four sources does not have.
   */
  async feed(
    userId: string,
    opts: DiscoveryOptions = {},
  ): Promise<SectionsEnvelope> {
    const offset =
      opts.cursor === undefined
        ? 0
        : this.#decodeFeedCursor(userId, opts.cursor);

    const envelope = await this.#blend(userId, {
      limit: opts.limit ?? 20,
      seedArtists: 2,
    });
    return this.#page(userId, envelope, offset);
  }

  /**
   * Recommendations for the authenticated account.
   *
   * The endpoint a personal API token exists for. It is the same blend as the
   * feed narrowed to the sections that are actually about this user, and it
   * deliberately exposes no raw upstream payload: Last.fm and MusicBrainz
   * licence their data for use, not for redistribution, so what crosses this
   * wire is Pull.fm's derived form with the attribution their terms require.
   */
  async recommendations(
    userId: string,
    opts: { seed?: string | undefined; limit?: number | undefined } = {},
  ): Promise<SectionsEnvelope> {
    const envelope = await this.#blend(userId, {
      limit: opts.limit ?? 20,
      // A seed asks for neighbourhoods rather than for the user's own history,
      // so it buys more shelves; without one, one shelf is enough.
      seedArtists: opts.seed === undefined ? 1 : 3,
    });
    const kinds = new Set(["made_for_you", "because_you_like", "daily_mix"]);
    return {
      ...envelope,
      sections: envelope.sections.filter((s) => kinds.has(s.kind)),
    };
  }

  // -------------------------------------------------------------------------
  // Stations
  // -------------------------------------------------------------------------

  /**
   * Stations generated for the account.
   *
   * A station is DERIVED, not stored: it is a seed artist plus the owner. There
   * is therefore no station row to address, and its identifier is a signed
   * value binding both. That is what makes `GET /v1/stations/:id/tracks` answer
   * 404 for a foreign identifier without a database lookup, and what stops a
   * station id from being a guessable integer.
   */
  async stations(userId: string): Promise<SectionsEnvelope> {
    const ports = await this.#ports(userId);
    let seeds: ArtistListenRef[] = [];
    const unavailable: string[] = [];
    try {
      seeds = await ports.listenbrainz.topArtists(8);
    } catch {
      unavailable.push("listenbrainz");
    }

    const items = seeds
      .filter(
        (a): a is ArtistListenRef & { artistMbid: string } =>
          a.artistMbid !== undefined,
      )
      .map((a) => ({
        type: "station" as const,
        id: this.stationId(userId, a.artistMbid),
        title: `${a.artistName} radio`,
        seed: { mbid: a.artistMbid, name: a.artistName },
        sources: ["listenbrainz:stats"],
        attribution: [LISTENBRAINZ_ATTRIBUTION],
      }));

    return {
      sections:
        items.length === 0
          ? []
          : [{ kind: "stations", title: "Your stations", items }],
      cursor: null,
      degraded: unavailable.length > 0,
      unavailableProviders: unavailable,
      attribution:
        items.length === 0 ? [] : [attributionOf(LISTENBRAINZ_ATTRIBUTION)],
    };
  }

  /** Tracks for one station. Throws 404 for an identifier this subject does not own. */
  async stationTracks(
    userId: string,
    stationId: string,
    limit = 20,
  ): Promise<SectionsEnvelope> {
    const seedMbid = this.#openStationId(userId, stationId);
    const ports = await this.#ports(userId);

    let tracks: RadioTrackRef[] = [];
    try {
      tracks = await ports.listenbrainz.artistRadio(seedMbid);
    } catch {
      return emptyEnvelope(["listenbrainz"]);
    }

    const items = tracks.slice(0, limit).map((t) => ({
      type: "track" as const,
      recordingMbid: t.recordingMbid,
      title: t.recordingName,
      artistName: t.artistName,
      artistMbid: t.artistMbid ?? null,
      score: t.similarity,
      sources: ["listenbrainz:lb-radio"],
      attribution: [LISTENBRAINZ_ATTRIBUTION],
    }));

    return {
      sections:
        items.length === 0
          ? []
          : [
              {
                kind: "because_you_like",
                title: "Station",
                seed: { mbid: seedMbid, name: seedMbid },
                items,
              },
            ],
      cursor: null,
      degraded: false,
      unavailableProviders: [],
      attribution:
        items.length === 0 ? [] : [attributionOf(LISTENBRAINZ_ATTRIBUTION)],
    };
  }

  // -------------------------------------------------------------------------
  // Catalogue. Owned by nobody, so no ownership predicate applies and none is
  // possible; rate limiting is the control that does (THREAT-MODEL T16).
  // -------------------------------------------------------------------------

  /**
   * Search, served entirely from our own crosswalk.
   *
   * No user request ever triggers a synchronous upstream search. The crosswalk
   * is warmed by every resolution the feed already performs, so it improves
   * with use rather than requiring a backfill before it is useful.
   */
  async search(query: string, limit = 20): Promise<SectionsEnvelope> {
    const artistKey = normalizeKey(query);
    const recordingKey = normalizeTitle(query);

    const [artists, recordings] = await Promise.all([
      this.#upstream.crosswalkStore.search(
        "artist",
        artistKey,
        SEARCH_MIN_SIMILARITY,
        limit,
      ),
      this.#upstream.crosswalkStore.search(
        "recording",
        recordingKey,
        SEARCH_MIN_SIMILARITY,
        limit,
      ),
    ]);

    const items = [
      ...artists.map((hit) => ({
        type: "artist" as const,
        artistMbid: hit.mbid,
        name: displayNameOf(hit),
        score: hit.similarity,
        sources: [hit.source],
        attribution: [MUSICBRAINZ_ATTRIBUTION],
      })),
      ...recordings.map((hit) => ({
        type: "track" as const,
        recordingMbid: hit.mbid,
        title: displayNameOf(hit),
        score: hit.similarity,
        sources: [hit.source],
        attribution: [MUSICBRAINZ_ATTRIBUTION],
      })),
    ]
      .sort((a, b) => b.score - a.score)
      .slice(0, limit);

    return {
      sections:
        items.length === 0
          ? []
          : [
              {
                kind: "search_results",
                title: `Results for "${query}"`,
                items,
              },
            ],
      cursor: null,
      degraded: false,
      unavailableProviders: [],
      attribution: items.length === 0 ? [] : [MUSICBRAINZ_ATTRIBUTION],
    };
  }

  /**
   * One artist.
   *
   * Two resolutions, and the response says which it got. A full MusicBrainz
   * record when one is cached; otherwise the name the crosswalk learned from
   * ListenBrainz, which is a thin but honest answer. A 404 here means "we have
   * never resolved this MBID", not "no such artist" - the distinction matters
   * because MusicBrainz cannot be consulted to tell them apart on a request
   * path that permits one call per second across the whole service.
   */
  async artist(mbid: string): Promise<ArtistView | null> {
    const cached = await this.#peekArtist(mbid);
    if (cached !== null) {
      return {
        mbid: cached.mbid,
        name: cached.name,
        sortName: cached.sortName ?? null,
        country: cached.country ?? null,
        beganYear: cached.beganYear ?? null,
        resolution: "musicbrainz",
        attribution: [MUSICBRAINZ_ATTRIBUTION],
      };
    }

    const name = await this.#nameFromCrosswalk("artist", mbid);
    if (name === null) return null;
    return {
      mbid,
      name,
      sortName: null,
      country: null,
      beganYear: null,
      resolution: "crosswalk",
      attribution: [MUSICBRAINZ_ATTRIBUTION],
    };
  }

  /**
   * Artists similar to one artist.
   *
   * Reachable without any user connection, because both sources are
   * app-credentialed: ListenBrainz labs takes no token, and Last.fm's key is
   * app-wide. That is why this route is authenticated-shared rather than
   * user-scoped.
   */
  async similarArtists(
    mbid: string,
    limit = 20,
  ): Promise<{
    artists: readonly {
      artistMbid: string | null;
      name: string;
      score: number;
      sources: readonly string[];
      attribution: readonly Attribution[];
    }[];
    degraded: boolean;
    unavailableProviders: readonly string[];
    attribution: readonly Attribution[];
  }> {
    const unavailable: string[] = [];
    const merged = new Map<
      string,
      {
        artistMbid: string | null;
        name: string;
        score: number;
        sources: Set<string>;
        attribution: Attribution[];
      }
    >();

    const add = (
      key: string,
      value: { artistMbid: string | null; name: string; score: number },
      source: string,
      attribution: Attribution,
    ): void => {
      const existing = merged.get(key);
      if (existing === undefined) {
        merged.set(key, {
          ...value,
          sources: new Set([source]),
          attribution: [attribution],
        });
        return;
      }
      // Agreement between two independent sources is the strongest signal this
      // route has, so it raises the score rather than merely deduplicating.
      existing.score = Math.min(1, existing.score + value.score * 0.5);
      existing.sources.add(source);
      if (!existing.attribution.some((a) => a.source === attribution.source)) {
        existing.attribution.push(attribution);
      }
      existing.artistMbid ??= value.artistMbid;
    };

    // labs.api returns [] rather than throwing on failure, by contract.
    for (const a of await this.#labsSimilarArtists(mbid)) {
      add(
        normalizeKey(a.name),
        { artistMbid: a.artistMbid ?? null, name: a.name, score: a.score },
        "listenbrainz:labs-similar",
        LISTENBRAINZ_ATTRIBUTION,
      );
    }

    const seedName = await this.#displayName("artist", mbid);
    if (seedName !== null && this.#upstream.lastfm !== undefined) {
      try {
        for (const a of await this.#lastfmSimilarArtists(seedName)) {
          add(
            normalizeKey(a.name),
            { artistMbid: a.artistMbid ?? null, name: a.name, score: a.score },
            "lastfm:similar",
            lastfmAttribution(a.url),
          );
        }
      } catch {
        unavailable.push("lastfm");
      }
    }

    const artists = [...merged.values()]
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((a) => ({
        artistMbid: a.artistMbid,
        name: a.name,
        score: Number(a.score.toFixed(4)),
        sources: [...a.sources].sort(),
        attribution: a.attribution,
      }));

    const sources = new Set(
      artists.flatMap((a) => a.attribution.map((x) => x.source)),
    );
    return {
      artists,
      degraded: unavailable.length > 0,
      unavailableProviders: unavailable,
      attribution: [...sources]
        .sort()
        .map((source) =>
          source === "lastfm"
            ? { source, text: LASTFM_ATTRIBUTION }
            : { source, text: LISTENBRAINZ_ATTRIBUTION.text },
        ),
    };
  }

  async track(mbid: string): Promise<TrackView | null> {
    const cached = await this.#peekRecording(mbid);
    if (cached === null) return null;
    return {
      mbid: cached.mbid,
      title: cached.title,
      artistName: cached.artistName,
      artistMbid: cached.artistMbid ?? null,
      durationMs: cached.lengthMs ?? null,
      resolution: "musicbrainz",
      attribution: [MUSICBRAINZ_ATTRIBUTION],
    };
  }

  async album(mbid: string): Promise<AlbumView | null> {
    const cached = await this.#upstream.cache.peek(
      "musicbrainz",
      `release:${mbid}`,
      parseCachedRelease,
    );
    if (cached === null) return null;
    return {
      mbid: cached.mbid,
      title: cached.title,
      artistName: cached.artistName,
      artistMbid: cached.artistMbid ?? null,
      date: cached.date ?? null,
      country: cached.country ?? null,
      trackCount: cached.trackCount ?? null,
      resolution: "musicbrainz",
      attribution: [MUSICBRAINZ_ATTRIBUTION],
    };
  }

  /**
   * A 30 second preview URL.
   *
   * The two providers are not interchangeable and this method is where that
   * asymmetry lives (docs/PLAN.md section 1a rule 4, docs/UPSTREAM-TERMS.md
   * L2/L3):
   *
   *   iTunes  Unsigned, no expiry, hotlinkable. Persisted in `track_previews`
   *           and served from there forever. `expiresAt` is null and
   *           `cacheable` is true.
   *   Deezer  Signed with an expiry (`?hdnea=exp=...~hmac=...`). Re-resolved
   *           LIVE, immediately before playback, and never persisted - not to
   *           `track_previews`, not to `upstream_cache`, not anywhere. The
   *           store rejects the write and `track_previews_deezer_expiry_chk`
   *           rejects it again at the schema. A stored Deezer URL passes every
   *           test written against a warm cache and then 403s for users.
   *
   * Apple additionally permit previews to be "streamed only, and not
   * downloaded, saved, cached, or synchronized", so only the resolved URL is
   * ever stored and never the audio.
   */
  async preview(mbid: string): Promise<PreviewView | null> {
    const stored = await this.#upstream.previews.resolveCached(mbid);
    if (stored !== null) {
      return {
        recordingMbid: mbid,
        provider: stored.provider,
        url: stored.url,
        durationMs: stored.durationMs ?? null,
        expiresAt: stored.expiresAt,
        cacheable: stored.cacheable,
        attribution: stored.attribution,
      };
    }

    // Deezer needs a name, and the only name available without spending a
    // MusicBrainz request is a cached one. No name means no preview, which is
    // an honest 404 rather than a lookup this route is not permitted to make.
    const recording = await this.#peekRecording(mbid);
    if (recording === null) return null;

    let live;
    try {
      live = await this.#upstream.previews.refreshForPlayback({
        recordingMbid: mbid,
        artistName: recording.artistName,
        title: recording.title,
      });
    } catch (err) {
      if (!isUpstreamError(err)) throw err;
      // A spent Deezer budget or an open breaker is "no preview right now",
      // which the client renders as a disabled play button, not as an error.
      return null;
    }
    if (live === null) return null;

    return {
      recordingMbid: mbid,
      provider: live.provider,
      url: live.url,
      durationMs: live.durationMs ?? null,
      expiresAt: live.expiresAt,
      cacheable: live.cacheable,
      attribution: live.attribution,
    };
  }

  // -------------------------------------------------------------------------
  // Identifiers. Signed rather than stored; see `stations` above.
  // -------------------------------------------------------------------------

  /** Mints a station identifier bound to one subject and one seed artist. */
  stationId(userId: string, seedMbid: string): string {
    const payload = Buffer.from(seedMbid, "utf8").toString("base64url");
    return `${payload}.${this.#keys.sign("cursor", `station|${userId}|${payload}`)}`;
  }

  /** Mints a feed cursor. Exposed so a test can hold one without a warm cache. */
  feedCursor(userId: string, offset: number): string {
    return encodeCursor(this.#keys, CURSOR_SCOPE_FEED, userId, {
      createdAt: new Date(0).toISOString(),
      id: String(offset),
    });
  }

  #openStationId(userId: string, stationId: string): string {
    // A single 404 for malformed, foreign, and unknown alike. Distinguishing
    // them would tell an attacker whether a guessed identifier was ever real.
    const reject = (): never => {
      throw errors.notFound("station");
    };
    const parts = stationId.split(".");
    if (parts.length !== 2) return reject();
    const [payload, mac] = parts as [string, string];
    if (payload.length === 0 || mac.length === 0) return reject();
    if (!this.#keys.verify("cursor", `station|${userId}|${payload}`, mac)) {
      return reject();
    }
    const seed = Buffer.from(payload, "base64url").toString("utf8");
    return MBID_RE.test(seed) ? seed : reject();
  }

  #decodeFeedCursor(userId: string, cursor: string): number {
    const position = decodeCursor(
      this.#keys,
      CURSOR_SCOPE_FEED,
      userId,
      cursor,
    );
    const offset = Number.parseInt(position.id, 10);
    if (!Number.isInteger(offset) || offset < 0) {
      throw errors.badRequest(
        "The cursor is not valid. Start from the first page.",
      );
    }
    return offset;
  }

  #page(
    userId: string,
    envelope: SectionsEnvelope,
    offset: number,
  ): SectionsEnvelope {
    const page = envelope.sections.slice(offset, offset + SECTIONS_PER_PAGE);
    const next = offset + SECTIONS_PER_PAGE;
    return {
      ...envelope,
      sections: page,
      cursor:
        next < envelope.sections.length ? this.feedCursor(userId, next) : null,
    };
  }

  // -------------------------------------------------------------------------
  // The blend, and the ports it runs on.
  // -------------------------------------------------------------------------

  async #blend(
    userId: string,
    opts: { limit: number; seedArtists: number },
  ): Promise<SectionsEnvelope> {
    const ports = await this.#ports(userId);
    return buildFeed(ports, {
      limit: opts.limit,
      seedArtists: opts.seedArtists,
      enableLastfm: this.#upstream.lastfm !== undefined,
    });
  }

  async #ports(userId: string): Promise<DiscoveryPorts> {
    const credential = await this.#connections.openCredential(
      userId,
      "listenbrainz",
    );

    return {
      listenbrainz: this.#listenBrainzPort(credential),
      ...(this.#upstream.lastfm === undefined
        ? {}
        : { lastfm: this.#lastfmPort() }),
      hydrate: {
        hydrateRecordings: (mbids) => this.#hydrate(mbids),
      },
    };
  }

  /**
   * The ListenBrainz port.
   *
   * `credential` is a closure argument holding plaintext for the lifetime of
   * one request. It is handed to the client and to nothing else.
   *
   * With no connection every method returns an empty result rather than
   * throwing, EXCEPT `topArtists`, which throws so `buildFeed` marks the feed
   * degraded. A user with no ListenBrainz account gets a 200 with no shelves
   * and `degraded: true`, which is the honest answer: we are not broken, we
   * simply do not know them yet.
   */
  #listenBrainzPort(
    credential: { providerAccountId: string; accessToken: string } | null,
  ): ListenBrainzPort {
    const client = this.#upstream.listenbrainz;
    const cache = this.#upstream.cache;

    if (credential === null) {
      return {
        recommendedRecordings: () => Promise.reject(NO_CONNECTION),
        topArtists: () => Promise.reject(NO_CONNECTION),
        artistRadio: () => Promise.reject(NO_CONNECTION),
        createdForPlaylists: () => Promise.reject(NO_CONNECTION),
        similarArtists: () => Promise.resolve([]),
      };
    }

    const user = credential.providerAccountId;
    // Bound once here so no method below closes over the credential object.
    const token = credential.accessToken;

    return {
      recommendedRecordings: async (
        limit,
      ): Promise<RecordingRecommendationRef[]> => {
        const result = await cache.fetch<RecordingRecommendationRef[]>({
          provider: "listenbrainz",
          // Keyed by the ListenBrainz account, which IS the subject for this
          // data. A key without it would serve one user's recommendations to
          // another (THREAT-MODEL T12).
          key: `cf:${user}:${String(limit)}`,
          ttlSeconds: TTL.recommendations,
          load: () => client.recommendedRecordings(user, token, limit),
          parse: (payload) =>
            asArray(payload).flatMap((row) => {
              const mbid = stringField(row, "recordingMbid");
              return mbid === null
                ? []
                : [
                    {
                      recordingMbid: mbid,
                      score: numberField(row, "score") ?? 0,
                    },
                  ];
            }),
        });
        return result.value;
      },

      topArtists: async (limit): Promise<ArtistListenRef[]> => {
        const result = await cache.fetch<ArtistListenRef[]>({
          provider: "listenbrainz",
          key: `top-artists:${user}:month`,
          ttlSeconds: TTL.topArtists,
          load: () => client.topArtists(user, token, "month"),
          parse: (payload) =>
            asArray(payload).flatMap((row) => {
              const name = stringField(row, "artistName");
              return name === null
                ? []
                : [
                    {
                      artistMbid: stringField(row, "artistMbid") ?? undefined,
                      artistName: name,
                      listenCount: numberField(row, "listenCount") ?? 0,
                    },
                  ];
            }),
        });
        return result.value.slice(0, limit);
      },

      artistRadio: async (artistMbid): Promise<RadioTrackRef[]> => {
        const result = await cache.fetch<RadioTrackRef[]>({
          // Not keyed by user: artist radio is a property of the artist, and
          // the response contains nothing about the caller. Keying it per user
          // would multiply the cost of a shared answer by the user count.
          provider: "listenbrainz",
          key: `lb-radio:${artistMbid}`,
          ttlSeconds: TTL.artistRadio,
          load: () => client.artistRadio(artistMbid, token),
          parse: (payload) =>
            asArray(payload).flatMap((row) => {
              const mbid = stringField(row, "recordingMbid");
              const name = stringField(row, "recordingName");
              if (mbid === null || name === null) return [];
              return [
                {
                  recordingMbid: mbid,
                  recordingName: name,
                  artistMbid: stringField(row, "artistMbid") ?? undefined,
                  artistName:
                    stringField(row, "artistName") ?? "Unknown Artist",
                  similarity: numberField(row, "similarity") ?? 0,
                },
              ];
            }),
        });
        // Radio results carry a recording MBID alongside its name, which is a
        // free, high-quality resolution. Feeding it back is what warms the
        // crosswalk without a backfill job, and is why search improves with use.
        await this.#learnRecordings(result.value);
        return result.value;
      },

      createdForPlaylists: async (): Promise<PlaylistRef[]> => {
        const result = await cache.fetch<PlaylistRef[]>({
          provider: "listenbrainz",
          key: `createdfor:${user}`,
          ttlSeconds: TTL.playlists,
          load: () => client.createdForPlaylists(user, token),
          parse: (payload) =>
            asArray(payload).flatMap((row) => {
              const identifier = stringField(row, "identifier");
              const title = stringField(row, "title");
              if (identifier === null || title === null) return [];
              return [
                {
                  identifier,
                  title,
                  annotation: stringField(row, "annotation") ?? undefined,
                },
              ];
            }),
        });
        return result.value;
      },

      similarArtists: (artistMbid) => this.#labsSimilarArtists(artistMbid),
    };
  }

  /**
   * labs.api similar artists. Returns [] on any failure, by its own contract.
   *
   * THE EXISTENCE CHECK LIVES INSIDE `load`, AND THAT PLACEMENT IS THE DESIGN.
   * `CachedUpstream.fetch` calls `load` only on a miss, so:
   *
   *   - a warm entry is served without the gate ever running, which makes it
   *     impossible for the gate to turn a cached answer into an empty one;
   *   - a declined lookup throws before the provider is touched, so `#fill`
   *     never reaches `store.set` and NO NEGATIVE IS CACHED. A dump loaded an
   *     hour later changes the answer immediately rather than after a seven-day
   *     TTL of wrong empties;
   *   - an EXPIRED entry still falls back to its stale payload, because a
   *     declined call takes the same path as a failed one.
   *
   * The route sees `[]`, which is what it already saw for an artist labs does
   * not know. Nothing on the wire changes; the upstream call does not happen.
   */
  async #labsSimilarArtists(artistMbid: string): Promise<SimilarArtistRef[]> {
    try {
      const result = await this.#upstream.cache.fetch<SimilarArtistRef[]>({
        provider: "listenbrainz",
        key: `labs-similar:${artistMbid}`,
        ttlSeconds: TTL.labsSimilar,
        load: async () => {
          if (!(await this.#artistGate.worthAsking(artistMbid))) {
            throw NOT_WORTH_ASKING;
          }
          return this.#upstream.listenbrainz.similarArtists(artistMbid);
        },
        parse: (payload) =>
          asArray(payload).flatMap((row) => {
            const name = stringField(row, "name");
            const score = numberField(row, "score") ?? 0;
            if (name === null) return [];
            return [
              {
                artistMbid: stringField(row, "artistMbid") ?? undefined,
                name,
                // labs scores are unbounded similarity counts, not
                // probabilities. Squashing keeps them comparable with Last.fm's
                // 0-1 `match` inside one merged shelf.
                score: score > 1 ? 1 - 1 / (1 + score) : score,
              },
            ];
          }),
      });
      return result.value;
    } catch {
      return [];
    }
  }

  /**
   * The Last.fm port.
   *
   * Everything here is app-credentialed: the per-user session key in the vault
   * is for writes we do not perform. TTLs are long because their 100 MB cache
   * cap is relieved by fewer, longer-lived rows.
   */
  #lastfmPort(): LastfmPort {
    return {
      similarArtists: (artistName) => this.#lastfmSimilarArtists(artistName),
      similarTracks: (artistName, title) =>
        this.#lastfmSimilarTracks(artistName, title),
    };
  }

  async #lastfmSimilarArtists(artistName: string): Promise<SimilarArtistRef[]> {
    const client = this.#upstream.lastfm;
    if (client === undefined) return [];
    const result = await this.#upstream.cache.fetch<SimilarArtistRef[]>({
      provider: "lastfm",
      key: `similar-artists:${normalizeKey(artistName)}`,
      ttlSeconds: TTL.lastfm,
      load: () => client.similarArtists(artistName, 20),
      parse: (payload) =>
        asArray(payload).flatMap((row) => {
          const name = stringField(row, "name");
          if (name === null) return [];
          return [
            {
              artistMbid: stringField(row, "mbid") ?? undefined,
              name,
              score: numberField(row, "match") ?? 0,
              // Their terms mandate this exact link format (ToS 2.7/4.2.2), so
              // it is reconstructed rather than trusted from the payload.
              url: stringField(row, "url") ?? artistUrl(name),
            },
          ];
        }),
    });
    return result.value;
  }

  async #lastfmSimilarTracks(
    artistName: string,
    title: string,
  ): Promise<SimilarTrackRef[]> {
    const client = this.#upstream.lastfm;
    if (client === undefined) return [];
    const result = await this.#upstream.cache.fetch<SimilarTrackRef[]>({
      provider: "lastfm",
      key: `similar-tracks:${normalizeKey(artistName)}:${normalizeTitle(title)}`,
      ttlSeconds: TTL.lastfm,
      load: () => client.similarTracks(artistName, title, 20),
      parse: (payload) =>
        asArray(payload).flatMap((row) => {
          const trackTitle = stringField(row, "title");
          const artist = stringField(row, "artistName");
          if (trackTitle === null || artist === null) return [];
          return [
            {
              title: trackTitle,
              artistName: artist,
              recordingMbid: stringField(row, "mbid") ?? undefined,
              score: numberField(row, "match") ?? 0,
              url: stringField(row, "url") ?? trackUrl(artist, trackTitle),
            },
          ];
        }),
    });
    return result.value;
  }

  /**
   * MBID -> display metadata, CACHE ONLY.
   *
   * `peek`, never `fetch`. MusicBrainz permits one request per second across
   * the whole service, so filling fifty misses here would take fifty seconds
   * and would spend the entire global budget on one feed render. A partial map
   * is the correct answer: `buildFeed` drops the items it cannot name, which
   * shrinks a shelf rather than failing a request.
   */
  async #hydrate(
    recordingMbids: readonly string[],
  ): Promise<Map<string, TrackRef>> {
    const out = new Map<string, TrackRef>();
    const unique = [...new Set(recordingMbids)];
    const found = await Promise.all(
      unique.map((mbid) => this.#peekRecording(mbid)),
    );
    for (const recording of found) {
      if (recording === null) continue;
      out.set(recording.mbid, {
        recordingMbid: recording.mbid,
        title: recording.title,
        artistName: recording.artistName,
        artistMbid: recording.artistMbid,
      });
    }
    return out;
  }

  // -------------------------------------------------------------------------
  // The MusicBrainz WARM path.
  //
  // Every MusicBrainz read in this application goes through `CachedUpstream`:
  // the request path uses `peek` (never calls out) and the fill uses `fetch`
  // (read-through, writes the row). At 1 req/s globally the cache is not an
  // optimisation, it is the mechanism that makes the limit survivable, and
  // Gate 2's warm-hit-rate target assumes it
  // (docs/compliance/metabrainz-terms-review.md F6).
  //
  // NO ROUTE CALLS THE METHODS BELOW, and that is the design rather than an
  // omission: filling fifty misses on a request path would take fifty seconds
  // and spend the entire global budget on one render. They are the sanctioned
  // entry point for the background resolver, and they exist now so that job is
  // a scheduler plus a query rather than a second, uncached code path written
  // under time pressure.
  //
  // TTL is 30 days rather than permanent. MusicBrainz core data is CC0 and
  // carries no cache cap, TTL requirement or systematic-storage limit - the
  // Last.fm 100 MB rule must not be copied here - but MBIDs do get merged and
  // titles corrected, so a row that never expires is a correction we never
  // pick up.
  // -------------------------------------------------------------------------

  async warmArtist(mbid: string): Promise<MusicBrainzArtist | null> {
    const result = await this.#upstream.cache.fetch<MusicBrainzArtist | null>({
      provider: "musicbrainz",
      key: `artist:${mbid}`,
      ttlSeconds: TTL.musicbrainz,
      load: () => this.#upstream.musicbrainz.lookupArtist(mbid),
      parse: parseCachedArtist,
    });
    return result.value;
  }

  async warmRecording(mbid: string): Promise<MusicBrainzRecording | null> {
    const result =
      await this.#upstream.cache.fetch<MusicBrainzRecording | null>({
        provider: "musicbrainz",
        key: `recording:${mbid}`,
        ttlSeconds: TTL.musicbrainz,
        load: () => this.#upstream.musicbrainz.lookupRecording(mbid),
        parse: parseCachedRecording,
      });
    return result.value;
  }

  async warmRelease(mbid: string): Promise<MusicBrainzRelease | null> {
    const result = await this.#upstream.cache.fetch<MusicBrainzRelease | null>({
      provider: "musicbrainz",
      key: `release:${mbid}`,
      ttlSeconds: TTL.musicbrainz,
      load: () => this.#upstream.musicbrainz.lookupRelease(mbid),
      parse: parseCachedRelease,
    });
    return result.value;
  }

  #peekRecording(mbid: string): Promise<MusicBrainzRecording | null> {
    return this.#upstream.cache.peek(
      "musicbrainz",
      `recording:${mbid}`,
      parseCachedRecording,
    );
  }

  #peekArtist(mbid: string): Promise<MusicBrainzArtist | null> {
    return this.#upstream.cache.peek(
      "musicbrainz",
      `artist:${mbid}`,
      parseCachedArtist,
    );
  }

  /** The best name we hold for an MBID, from the cache or the crosswalk. */
  async #displayName(
    entity: "artist" | "recording",
    mbid: string,
  ): Promise<string | null> {
    if (entity === "artist") {
      const cached = await this.#peekArtist(mbid);
      if (cached !== null) return cached.name;
    } else {
      const cached = await this.#peekRecording(mbid);
      if (cached !== null) return cached.title;
    }
    return this.#nameFromCrosswalk(entity, mbid);
  }

  /**
   * The crosswalk stores name -> MBID, so this is the reverse direction and it
   * returns the NORMALISED key rather than the original casing. Thin, but true;
   * the wire carries `resolution: "crosswalk"` so a client can present it as
   * provisional rather than as MusicBrainz's canonical name.
   */
  async #nameFromCrosswalk(
    entity: "artist" | "recording",
    mbid: string,
  ): Promise<string | null> {
    const hit = await this.#upstream.crosswalkStore.lookupByMbid(entity, mbid);
    return hit === null ? null : hit.normalizedKey;
  }

  /** Records (name, mbid) pairs a provider already resolved for us. */
  async #learnRecordings(tracks: readonly RadioTrackRef[]): Promise<void> {
    await Promise.allSettled(
      tracks.flatMap((track) => {
        const jobs = [
          this.#upstream.crosswalk.learn(
            "recording",
            `${track.artistName} ${track.recordingName}`,
            track.recordingMbid,
            "listenbrainz:lb-radio",
          ),
        ];
        if (track.artistMbid !== undefined) {
          jobs.push(
            this.#upstream.crosswalk.learn(
              "artist",
              track.artistName,
              track.artistMbid,
              "listenbrainz:lb-radio",
            ),
          );
        }
        return jobs;
      }),
    );
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const MBID_RE =
  /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

const LISTENBRAINZ_ATTRIBUTION: Attribution = {
  source: "listenbrainz",
  text: "Recommendations by ListenBrainz",
  url: "https://listenbrainz.org",
};

const NO_CONNECTION = new Error("no ListenBrainz connection for this subject");

/**
 * Signals "do not spend an upstream call on this identifier".
 *
 * A thrown sentinel rather than a return value, because the decision has to
 * happen inside `CachedUpstream.fetch`'s `load` closure - the only place that
 * runs on a miss and not on a hit - and `load` must produce a payload or fail.
 * Failing is the correct shape anyway: `#fill` then writes nothing, so a
 * declined lookup leaves no trace to invalidate later.
 */
const NOT_WORTH_ASKING = new Error(
  "artist mbid is not known to any local record; declining the upstream call",
);

function attributionOf(a: Attribution): Attribution {
  return { source: a.source, text: a.text };
}

function lastfmAttribution(url: string | undefined): Attribution {
  return {
    source: "lastfm",
    text: LASTFM_ATTRIBUTION,
    ...(url === undefined ? {} : { url }),
  };
}

function emptyEnvelope(unavailable: readonly string[]): SectionsEnvelope {
  return {
    sections: [],
    cursor: null,
    degraded: unavailable.length > 0,
    unavailableProviders: [...unavailable],
    attribution: [],
  };
}

function displayNameOf(hit: CrosswalkHit): string {
  return hit.normalizedKey;
}

function asArray(payload: unknown): unknown[] {
  return Array.isArray(payload) ? payload : [];
}

function stringField(row: unknown, key: string): string | null {
  if (row === null || typeof row !== "object") return null;
  const value = (row as Record<string, unknown>)[key];
  return typeof value === "string" && value.length > 0 ? value : null;
}

function numberField(row: unknown, key: string): number | null {
  if (row === null || typeof row !== "object") return null;
  const value = (row as Record<string, unknown>)[key];
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function parseCachedArtist(payload: unknown): MusicBrainzArtist | null {
  const mbid = stringField(payload, "mbid");
  const name = stringField(payload, "name");
  if (mbid === null || name === null) return null;
  // Nothing reads `tags` off a cached row even if an older build wrote one:
  // supplementary MusicBrainz data is CC BY-NC-SA 3.0 and this response is
  // CC0-only. A row written before the client stopped requesting them is
  // therefore forward-compatible rather than a licence problem.
  return {
    mbid,
    name,
    sortName: stringField(payload, "sortName") ?? undefined,
    country: stringField(payload, "country") ?? undefined,
    beganYear: numberField(payload, "beganYear") ?? undefined,
  };
}

function parseCachedRecording(payload: unknown): MusicBrainzRecording | null {
  const mbid = stringField(payload, "mbid");
  const title = stringField(payload, "title");
  if (mbid === null || title === null) return null;
  return {
    mbid,
    title,
    lengthMs: numberField(payload, "lengthMs") ?? undefined,
    artistMbid: stringField(payload, "artistMbid") ?? undefined,
    artistName: stringField(payload, "artistName") ?? "Unknown Artist",
  };
}

function parseCachedRelease(payload: unknown): MusicBrainzRelease | null {
  const mbid = stringField(payload, "mbid");
  const title = stringField(payload, "title");
  if (mbid === null || title === null) return null;
  return {
    mbid,
    title,
    date: stringField(payload, "date") ?? undefined,
    country: stringField(payload, "country") ?? undefined,
    trackCount: numberField(payload, "trackCount") ?? undefined,
    artistMbid: stringField(payload, "artistMbid") ?? undefined,
    artistName: stringField(payload, "artistName") ?? "Unknown Artist",
  };
}

/** Re-exported so the route module does not import from two packages. */
export type { FeedSection, SectionsEnvelope };
